project: 
  type: website
  output-dir: docs

website: 
  title: "Diego Gonzalez"
  site-url: "https://diegogonzalez.dev"
  description: "A website showcasing my CV and my project portfolio for electrical engineering, computer science, and mathematics projects"
  favicon: "favicon.ico"
  page-navigation: true

  navbar:
    left:
      - text: "Home"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "About Me"
        file: about.qmd
      - text: "CV"
        file: cv.qmd
    right: 
      - icon: github
        href: https://github.com/diegogonzalez5813
      - icon: linkedin
        href: https://linkedin.com/in/diego-gonzalez-aa1a24378 

  page-footer:
    left: "&copy; Copyright 2025, Diego Gonzalez"
    right: "Innovation in service of others."

format:
  html: 
    theme: [flatly, _variables.scss]
    code-link: true
    code-copy: true
    code-overflow: wrap

search: true

editor: visual